packages:
  - 'packages/*'
allowBuilds:
  '@ffprobe-installer/darwin-arm64': true
  '@ffprobe-installer/darwin-x64': true
  '@ffprobe-installer/linux-arm': true
  '@ffprobe-installer/linux-arm64': true
  '@ffprobe-installer/linux-ia32': true
  '@ffprobe-installer/linux-x64': true
  '@ffprobe-installer/win32-ia32': true
  '@ffprobe-installer/win32-x64': true
  better-sqlite3: true
  electron: true
  esbuild: true
  ffmpeg-static: true
  sharp: true
